print("<html>")
print("<head>")
print("<title>CGI GET</title>")
print("<style>")
print("body {")
print("    font-family: Arial, sans-serif;")
print("    margin: 0;")
print("    padding: 20px;")
print("    background-color: #f5f5f5;")
print("}")
print("h1 {")
print("    color: #333;")
print("    text-align: center;")
print("}")
print("</style>")
print("</head>")
print("<body>")
print("<h1>Hello from Python :)</h1>")
print("</body>")
print("</html>")
